### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by vsatyakumar** [ideonate/jupyter-innotater#1]
<img width="1003" alt="Screen Shot 2019-06-04 at 9 39 35 PM" src="https://user-images.githubusercontent.com/4519872/58924301-5c0c1400-8711-11e9-92f8-b82db06bc623.png">

**Comment by danlester** [comment]
Thank you for reporting this issue. The problem is that you are using a Python 2.7 kernel but the Innotater is only designed to run on Python 3 (e.g. Python 3.7).

I think it makes sense for Innotater not to support Python versions lower than 3.3 because the underlying Jupyter code for Python (IPython) has itself dropped support for such versions, as have some fundamental machine learning libraries such as NumPy.

So it is likely to make sense for you to try using a more recent version of Python anyway. How to do this may depend on exactly how you have set up your Jupyter environment, and the machine you are using. The easiest thing is to manage virtual Python environments using [Anaconda](https://www.anaconda.com/). It might take a bit of time to switch to this approach, but I am sure you will be happier in the long run!

I am happy to provide more guidance if you get stuck, but it might be more appropriate to do that over email: dan@ideonate.com.

For future versions of Innotater I will see if it can output a more meaningful error message to explain the situation if the wrong version of Python is running.

**Comment by vsatyakumar** [comment]
Thanks for the prompt reply on this issue and all the great work!
