### ISSUE TITLE
Any tips on making it work on Google Colab?

### ISSUE THREAD

**Issue by orm011** [ideonate/jupyter-innotater#18]
Hi there, 

I really value your tool, thanks for making it.  I've used it on jupyter notebook, and it works perfectly for me.
A few students I work with use the colab notebook, and for them the innotator widgets don't display (at all). 

The chrome developer console shows an error:
"Error has occurred while trying to update output."
"Error: Widgets module jupyter-innotater is not supported"

I'm not sure if you can think of an easy work around for this, it would be helpful.
Other ipywidgets do work fine. 

I copied one of your examples into a colab notebook to reproduce the issue in case it helps.
https://colab.research.google.com/drive/1ANFSGUyX3K_6DaZJCgZWPHGYyGOnOb0T?usp=sharing

On a potentially related note, I noticed when I installed jupyter_innotator on the notebook that I need to install the package both on the kernel env and on the notebook env  (I use a single notebook for multiple kernels, so they are actually in different python environments).  This makes some sense, because there is both browser and python logic involved. Before I did that, I found a similar error when I only installed the package on the kernel environment, and not on the notebook one.

**Comment by danlester** [comment]
@orm011 Thank you for your issue, and especially for providing the notebook so I could try it out myself. I'm pleased to hear you like the Innotater!

I don't know enough about Colab to be sure, but I think it's unlikely that extensions such as Innotater are supported.

I know ipywidgets work, but that is a more standard part of Jupyter.

I tried [pyleaflet](https://ipyleaflet.readthedocs.io/en/latest/usage.html) as another example of a more involved but third party widget, which is well maintained, and I can't get that to work either. It fails in the same way.

The Javascript components would need to be loaded with the overall Colab page and I think it is unlikely to happen really.

To be sure, you would need to find out from Google Colab whether they support Jupyter widgets somehow. I have been able to get Innotater working in Kaggle, but there are specific options for creating extended environments there, so that's how it works in that case.

Anyone reading, please let us know if you know more! I will close the issue for now because I do think Colab needs to support extensions for this to work, but anyone should feel free to reopen if they know more...
