### ISSUE TITLE
JupyterLab support

### ISSUE THREAD

**Issue by neighthan** [ideonate/jupyter-innotater#2]
I assume, based on the install instructions, that this project does not support JupyterLab? (also, trying to test the first example from the README doesn't yield any useful output; see below). Do you plan to introduce such support or is that outside of the scope of this project?

Running this code

```python
import os
import numpy as np
import matplotlib.pyplot as plt
from jupyter_innotater import Innotater, ImageInnotation, BoundingBoxInnotation

img = plt.imread("roadrunner.png")  # any test image
targets = np.zeros((1, 4))
Innotater(ImageInnotation([img]), BoundingBoxInnotation(targets))
```

gives me the following

`Innotater(children=(HBox(children=(VBox(children=(ImagePad(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00…`

but no widgets or images displayed. I just tested in a classic Notebook, and it seems to work fine there.

**Comment by danlester** [comment]
Thank you for your comments - it's really helpful to have feedback to understand how people are using Innotater!

JupyterLab support is something I will certainly add. Last time I looked, the support for extensions in JupyterLab was fairly experimental and subject to change, so I didn't invest the time in writing for the then-current API. I'll take another look over the next few weeks to see if it's stable enough to make the changes now - it should be since it is hovering around a 1.0.0 alpha release.

**Comment by neighthan** [comment]
Okay, glad to hear that's on the roadmap, but you are right that the API is still not stable (see, e.g., the [dev docs]), though hopefully that will change soon (since 1.0 was expected late last year)

[dev docs]: https://jupyterlab.readthedocs.io/en/latest/developer/extension_dev.html

**Comment by danlester** [comment]
I've had a quick look at both the stable (~0.35) and latest (~1.0) versions of jupyterlab and I still think I will wait for the official release of 1.0 to gauge best-practices from other extensions at that time.

**Comment by danlester** [comment]
Innotater now works in Jupyter Lab (1.0+)!

After upgrading to the Python package 0.1.7 (pip install jupyter_innotater -U), you may also need to run:

jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-innotater

Please everyone try it out and let me know of any problems!
