### ISSUE TITLE
RBG-formatted images?

### ISSUE THREAD

**Issue by neighthan** [ideonate/jupyter-innotater#4]
In the [documentation], it says that images passed directly as `numpy` arrays should be in RGB format. However, this doesn't seem to be the case. I've loaded an image in RGB format using `matplotlib`'s `imread` and displayed it using `imshow` (which uses RGB format for 3-channel images), and here's the comparison with the image shown by `Innotator`:

Matplotlib
<img src="https://user-images.githubusercontent.com/12573501/59218099-66089980-8b8d-11e9-8f13-932d7d84d1a2.png" width=300>

Innotator
<img src="https://user-images.githubusercontent.com/12573501/59218125-77ea3c80-8b8d-11e9-8a2e-b5f6070d8538.png" width=300>

```python
import os
import numpy as np
import matplotlib.pyplot as plt
from jupyter_innotater import Innotater, ImageInnotation, BoundingBoxInnotation

# image is RGBA; drop alpha channel
img = plt.imread("roadrunner.png")[..., :-1]
plt.figure(figsize=(8,8))
plt.imshow(img)
plt.axis("off")

targets = np.zeros((1, 4))
Innotater(ImageInnotation([img]), BoundingBoxInnotation(targets))
```

[documentation]: https://jupyter-innotater.readthedocs.io/en/latest/chapters/usage.html?highlight=rgb

**Comment by danlester** [comment]
Thanks for reporting this. I will have to take a look - possibly the docs should just read BGR... but the widget tries to do some 'helpful' interpretation of the data to understand the best way to display things, so it's possible it's getting it wrong in this instance. In any case, it could make sense to have an option to override the guesswork so it can be ultimately up to the user to dictate.

**Comment by neighthan** [comment]
Are you using `cv2.imread` when you load images from files? If so, that's BGR by default, which is what this image looks like, so updating the docs probably suffices (unless, as you say, you want to allow the user to say which format to use).

**Comment by danlester** [comment]
Yes you are right in that the default of BGR as loaded by cv2.imread was assumed.

In the latest development version this is corrected in the docs and also a new parameter `colorspace` can be specified to ImageInnotation to say the array should be interpreted as 'RGB' instead. Just provide `colorspace='RGB'`.

Latest relevant [docs are here](https://jupyter-innotater.readthedocs.io/en/latest/chapters/usage.html#imageinnotation).

I have also removed a dependency on Open CV2 which was being used for some of the numpy-related manipulation but wasn't added to requirements.txt because I understand it can be difficult to install. I didn't want to prevent installation for users who weren't using this functionality anyway. The latest version will attempt to use Open CV2 if available but will fall back on a pure-python alternative if needed.
