### ISSUE TITLE
Format options for drawing bounding boxes

### ISSUE THREAD

**Issue by neighthan** [ideonate/jupyter-innotater#5]
Depending on the image, it may be hard to see the bounding box. It would be nice to be able to set basic parameters for how the box is drawn (line width and color, and possible style (e.g. dashed, dotted, solid), should suffice). Here's an example where the bounding box around the roadrunner (in red) is hard to see.

<img src="https://user-images.githubusercontent.com/12573501/59218435-40c85b00-8b8e-11e9-81fd-b905f8b4cd7b.png" width=300>

**Comment by danlester** [comment]
Where there are multiple bounding boxes, only the 'current' box is green and the others are dotted black-and-white. I think the contrast is worse in the green case. Anyway, yes, this is a great suggestion. I could probably come up with better defaults, and then allowing the user to override them would mean the colors can be set most appropriately for the dataset.

Thanks again for all of your suggestions - I really appreciate your time in trying it out and sharing your thoughts. Hopefully I'll get a chance to take a proper look at your queries later this week; I won't be available much next week, but can pick up fully after that.

Please could you get in touch with me by email so that we can have a more direct dialogue about the way you've been using the Innotater? dan@ideonate.com - to understand your usage more generally would really help guide product development going forward aside from specific issues.

Thank you!

**Comment by danlester** [comment]
In the latest dev version there is an experimental `annotation_styles` parameter that can be passed  to the `ImageInnotation` constructor in order to control the bounding box styles.

Latest ImageInnotation [docs are here](https://jupyter-innotater.readthedocs.io/en/latest/chapters/usage.html#imageinnotation)

The example:

```python
ImageInnotation( images, annotation_styles = {
      'color1': '#FF0000', /* strokeStyle in Javascript context */
      'color2': '#00FF00', /* For second color of the dashed line */
      'lineWidth': 5, /* lineWidth in JS context */
      'lineDash': [10, 1, 5], /* Passed to setLineDash, can take one int instead of array */
      'selected_color2': '#FFFFFF', /* color1 but for currently-selected box */
      'selected_color2': '#0000AA', /* color2 for currently-selected box */
} )
```

The lineDash and lineWidth properties can be used to set a dotted line e.g.  'lineWidth': 5,  'lineDash': [5, 5].

To have just an unbroken line, set color1 to be equal to color2 (and selected_color1 equal to selected_color2).
