### ISSUE TITLE
support voila for creating stand alone app

### ISSUE THREAD

**Issue by ibayer** [ideonate/jupyter-innotater#7]
# Support Voila

Thanks for releasing this inspiring project!

I'm trying to use voila[0] to turn jupyter-innotater into a stand alone app. Currently I'm facing a range of error messages in the browser console that indicate that innotater is currently
not compatible with voila.

I believe fixing this has huge benefits especially when non technical people are involved into the labeling process.

Voila [0] is popular project that allows to turn interactive jupyter notebooks into standalone apps just by serving them with `voila example.ipynb`.

# Reproducing

```
[tool.poetry.dependencies]
python = "^3.7"
jupyter_innotater = { path = "./jupyter-innotater/jupyter-innotater" }
jupyter = "^1.0.0"
jupyterlab = "^1.1.4"
nbconvert = ">=5.5"
ipywidgets = "^7.5.1"
pandas = "^0.25.1"
opencv-python = "^4.1.1"
voila = "^0.1.17"
[tool.poetry.dev-dependencies]
```

Ensure that current setup is properly configured by running example from
voila repo.

`voila notebooks/interactive.ipynb` 

Running the innotator example with the same setup

`voila jupyter-innotater/Example/FlatImages.ipynb`

doesn't work:

browser
![image](https://user-images.githubusercontent.com/1497140/68542127-36aec080-03a9-11ea-8083-11956a399726.png)

![image](https://user-images.githubusercontent.com/1497140/68542065-509bd380-03a8-11ea-8e2b-44ecac3280b7.png)

The following voila discussions might be helpful to track down why innotator isn't compatible with
voila.

- https://github.com/voila-dashboards/voila/pull/46
- https://github.com/voila-dashboards/voila/issues/85

[0] https://github.com/voila-dashboards/voila

**Comment by danlester** [comment]
Thank you for reporting this issue. It makes a lot of sense to use Voila for this!

However, things seem to work for me. Possibly because it's now picking up a slightly newer version of Voila, but I'm not sure.

To try to reproduce this even more closely, how do you feel about trying docker? This is exactly what I've tried:

```
# From my Mac OS terminal
docker run -it -p 8866:8866 python:3.7 /bin/bash

# Now inside the docker container, install poetry
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

source $HOME/.poetry/env

cd /usr/src

poetry new voilainnotater

cd voilainnotater/

git clone https://github.com/ideonate/jupyter-innotater.git

# Just to install vim so we can edit the toml file
apt-get update
apt-get install vim

vim pyproject.toml
# <Insert extra dependencies from your toml file above>

poetry install

poetry shell

voila jupyter-innotater/Example/FlatImages.ipynb

# Then at localhost:8866 on my usual Mac browser, everything seems to work as expected.
```

Of course, this requires docker to be running first... If you have any questions about how to set this up, please let me know. I look forward to hearing how you get on.

If docker isn't feasible for you, please try again just to see if voila 0.1.18 helps. If not, I perhaps need to know more about your OS, and whether anything else could be interfering.

I haven't researched voila enough to fully understand how the Innotater Javscript side of things is loaded in the browser, but again it seems to work with the steps above!

Thanks,

Dan

**Comment by ibayer** [comment]
@danlester 

Thanks for taking the time to provide the Dockerfile. After upgrading to voila 0.1.18 and recreating my virtual env I can confirm that innotater + voila works for me locally as well . Not sure if the upgrade was necessary.

**Comment by danlester** [comment]
OK great, thanks for letting me know.

It would be really interesting to hear more about your project in general - please email dan@ideonate.com if you'd like to discuss.

I have some ideas that might be useful in the context of Voila so it would be good to compare notes.

Dan
